### ISSUE TITLE
Fehlermeldung: SocketTimeoutException 

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#44]
Bitte die Ursache für das SocketTimeout anschauen - danke.
Den Antrag haben wir dann wiederholt per Antragsnummer abholen können.

1062	6009	1	1	BX4251		28.03.19 10:12:51,685000000	28.03.19 10:12:41,463000000	FEHLER	java.net.SocketTimeoutException	SocketTimeoutException: Read timed out	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag BX4251/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:118)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)
	at de.sdvrz.epa.core.EpaControl.starteMapping(EpaControl.java:281)
	at de.sdvrz.epa.core.EpaControl.verarbeiteAntrag(EpaControl.java:234)
	at de.sdvrz.epa.core.EpaControl.lambda$verarbeiteEuropaceAntraege$0(EpaControl.java:195)
	at java.util.Optional.ifPresent(Optional.java:159)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEuropaceAntraege(EpaControl.java:183)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEpaKonfig(EpaControl.java:112)
	at de.sdvrz.epa.core.EpaControl.verarbeiteMandanten(EpaControl.java:85)
	at de.sdvrz.epa.core.EpaScheduler.epaAblauf(EpaScheduler.java:73)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
Caused by: java.io.IOException: org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.SocketTimeoutException: timeout
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.updateAccessToken(OAuth.java:143)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.retryingIntercept(OAuth.java:90)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.intercept(OAuth.java:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:88)
	... 19 more
Caused by: org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.SocketTimeoutException: timeout
	at de.sdvrz.epa.clientlib.handler.auth.OAuthOkHttpClient.execute(OAuthOkHttpClient.java:64)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:71)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.updateAccessToken(OAuth.java:132)
	... 27 more
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at de.sdvrz.epa.clientlib.handler.auth.OAuthOkHttpClient.execute(OAuthOkHttpClient.java:57)
	... 31 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 51 more
"

**Comment by oliverharendt** [comment]
@u00kram Ist der Fehler hier nochmal aufgetreten oder können wir das Ticket schließen?

**Comment by u00kram** [comment]
siehe #46 - gleicher Fehler oder irre ich mich. 
Ja der Fehler tritt noch auf - zuletzt am 6.3.20

**Comment by oliverharendt** [comment]
Ja das sieht mir nach eine Duplikat aus. Ich schließe das Issue und wir behandeln das Thema in #46 weiter.
