### ISSUE TITLE
Fehler: OAuthProblemException

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#45]
Bitte die Ursache für OAuthProblemException anschauen - danke.
Hinweis der Entwicklung: PartnerID und API Key für den entsprechenden TechnUser werden immer mitgegeben.

989	6009	1	1	V86264		22.03.19 11:22:38,356000000	22.03.19 11:22:38,133000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag V86264/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:118)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)
	at de.sdvrz.epa.core.EpaControl.starteMapping(EpaControl.java:281)
	at de.sdvrz.epa.core.EpaControl.verarbeiteAntrag(EpaControl.java:234)
	at de.sdvrz.epa.core.EpaControl.lambda$verarbeiteEuropaceAntraege$0(EpaControl.java:195)
	at java.util.Optional.ifPresent(Optional.java:159)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEuropaceAntraege(EpaControl.java:183)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEpaKonfig(EpaControl.java:112)
	at de.sdvrz.epa.core.EpaControl.verarbeiteMandanten(EpaControl.java:85)
	at de.sdvrz.epa.core.EpaScheduler.epaAblauf(EpaScheduler.java:73)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
Caused by: java.io.IOException: OAuthProblemException{error='invalid_request', description='Missing parameters: access_token', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.updateAccessToken(OAuth.java:145)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.retryingIntercept(OAuth.java:90)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.intercept(OAuth.java:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:88)
	... 19 more
Caused by: OAuthProblemException{error='invalid_request', description='Missing parameters: access_token', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
	at org.apache.oltu.oauth2.common.utils.OAuthUtils.handleOAuthProblemException(OAuthUtils.java:167)
	at org.apache.oltu.oauth2.common.utils.OAuthUtils.handleMissingParameters(OAuthUtils.java:185)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateRequiredParameters(OAuthClientValidator.java:90)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateParameters(OAuthClientValidator.java:53)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:49)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:64)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:59)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:52)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:60)
	at de.sdvrz.epa.clientlib.handler.auth.OAuthOkHttpClient.execute(OAuthOkHttpClient.java:58)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:71)
	at de.sdvrz.epa.clientlib.handler.auth.OAuth.updateAccessToken(OAuth.java:132)
	... 27 more

**Comment by ollio** [comment]
Aktuell ist es noch nicht möglich am Auth Server das ACCESS_TOKEN zu refreshen (aktualisieren). Daran arbeiten wir grade. 
Workaround bitte mit PartnerId und ApiKey täglich einloggen und ein neues Token holen. Dies sollte aktuell 24 Stunden gültig sein (OAuth1) An der Implementierung von OAuth 2 arbeiten wir grade.

**Comment by u00kram** [comment]
Rückmeldung von unserer Entwicklung / Herr Tauber:
vielen Dank - aber das Feedback zu unserer Anfrage ist nicht hilfreich. Unsere Client Anwendung verwendet ein auf Code Generierung basierenden Retrofit Client wie auf der Europace Github Seite der Antraege API beschrieben.
Der nach Anleitung generierte Client sieht keinen manuellen Login vor, der jeden Tag neu ausgeführt werden könnte.
Laut https://github.com/europace/baufismart-antraege-api/ setzt Antraege API auf OAuth2 auf:
Die Authentifizierung läuft über den OAuth2 Flow vom Typ ressource owner password credentials flow. https://tools.ietf.org/html/rfc6749#section-1.3.3
Bitte auf Github AntraegeAPI im Folgenden lesen ... Auch weist der generierte und bereits seit einem Jahr in Verwendung befindliche Quellcode auf die Verwendung von OAuth2 hin.
Für uns ist die Fehlersituation, als auch Ihre Erklärung nicht nachvollziehbar.

**Comment by u00kram** [comment]
Hallo zusammen,
der Fehler besteht weiterhin - würde fast sagen, er häuft sich.
Hier die drei Anträge von BW und Nbg. aus der letzten Woche.
Bitte dem Problem nochmal auf den Grund gehen. Der vorgeschlagene Workaround ist nicht durchführbar.
Danke!! VG, M.Kränz


2079 	6009	1	1	S12191	3348930001	14.05.19 15:51:47,259000000	14.05.19 15:20:09,094000000	BEENDET	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag S12191/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

2144	 7609	3	2	LL3216		17.05.19 10:10:09,230000000	17.05.19 10:10:08,947000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag LL3216/2
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	
	"
2139	 6009	1	1	F32479		17.05.19 08:50:10,147000000	17.05.19 08:50:09,793000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag F32479/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)

**Comment by ollio** [comment]
Wie bereits geschrieben, arbeiten wir am OAuth2.0 Flow. Die Umsetzung für die API-Logins ist mit Abschluss der Phase 2 geplant. Wenn der Flow implementiert ist, werden wir ein News Update schicken.

**Comment by ollio** [comment]
@u00kram versuchen Sie doch mal das Access Token bei validate anzugeben: OAuthProblemException{error='invalid_request', description='Missing parameters: access_token', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
Ich kenne leider Ihren Client Code nicht

**Comment by u00kram** [comment]
Hallo zusammen,
anlehnend an unsere Info vom 2. April hier nochmal die Rückmeldung von Herrn Tauber dazu:
"Wir verstehen, dass nicht jeder Client Code für den Zugriff auf die API bekannt sein kann. Wie bereits geschrieben wird aber der Client Quellcode exakt nach den Vorgaben zur "Generierung des Clients" des README erzeugt. Wir sehen in der Generierung eines API Clients auf Swagger (OpenAPI) Spezifikation auch die Beste Lösung für den Zugriff auf REST Schnittstellen. Ein simples Aufrufen der API mittels Testtools wie Postman ist für eine automatisierte Verarbeitung von Anträgen keine Alternative. Auch die manuelle Erstellung von Http Anfragen und Aufbau eines eigenen Client Frameworks kann keine Lösung sein.
Wir sind der Meinung, dass der vorgeschlagene Weg zum Aufruf mittels eines Retrofit / OkHttp Clients auf Seiten von Europace bekannt und getestet sein muss. Sonst hat diese Anleitung als einzig beschriebene Lösung für den Zugriff keine Rechtfertigung im README. 

Bei dem nach Anleitung generierten Client werden technische Details auf höherem Abstraktionsniveau gekapselt. Eine Möglichkeit eines validate(!?!) existiert nicht. Der OAuth Flow ist (wie er soll) durch den generierten Client verborgen.
Laut README basiert die API bereits auf OAuth2 und einem Login Endpunkt, weshalb wir nicht 100% sicher sind, welchen Inhalt Phase 2 haben soll. Neben einem News Update würden wir uns eine technische Beschreibung zur Anbindung der API mittels eines aus der Schnittstellen Beschreibung generierten Java Clients wünschen, so dass eine automatisierte Verarbeitung von Anträgen möglich bleibt."

Bitte geben Sie uns dazu eine entsprechende Rückinfo. Sonst drehen wir uns bei dem Thema im Kreis. Sinn macht auch ein direktes Telefonat mit Herrn Tauber, dann kommen schneller zum Ziel.
+49 911 9291-2532
Danke, VG, Manuela Kränz

**Comment by ollio** [comment]
Können Sie das Script posten, mit dem Sie Ihren Client erstellen? Ich würde dann einen Client auf gleiche Weise generieren und unsere Tests mit Ihrem Client laufen lassen.

**Comment by u00kram** [comment]
Mail vom 8.7.19 nach Telefonat:

Hallo Herr Otzen,
danke für Ihren Rückruf letzte Woche Freitag. Wie mit ihnen besprochen bauen wir unseren Retrofit/OkHttp Client exakt nach den Vorgaben von Europace auf Github Seite der BaufiSmart AntraegeAPI auf.
Derzeitig sehe ich keine Möglichkeit im Client Code Anpassung durchzuführen um den OAuth Bug zu beseitigen. 
Ich fände es tatsächlich gut, wenn Sie sich selbst den Client generieren und damit Ihre Tests fahren. So kann der Fehler evtl. bei ihnen reproduziert werden und es würde tatsächlich mit identischer Aufruf Logik gearbeitet.

Wie besprochen, schicke ich Zeitstempel, zu welcher Zeit wir Fehler in Produktion hatten. Vielleicht sehen sie eine Ursache in den Log Dateien (Trace-ID hat das Prefix SDV-IT_).
Allerdings sind diese Fehler schon ein paar Tage her. 

2144	7609	3	2	LL3216		17.05.19 10:10:09,230000000	17.05.19 10:10:08,947000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag LL3216/2
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	
	"
2139	6009	1	1	F32479		17.05.19 08:50:10,147000000	17.05.19 08:50:09,793000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag F32479/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)


"
2079	6009	1	1	S12191	3348930001	14.05.19 15:51:47,259000000	14.05.19 15:20:09,094000000	BEENDET	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag S12191/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

Hier ist die manuell angestoßene Wiederholung erfolgt - deshalb auf BEENDET.

Laut unserem Telefonat wird derzeitig der OAuth Workflow der API überarbeitet. Nach dem Umbau sollen die derzeitigen OAuth Probleme behoben sein.
Bis zur Behebung sehen wir beim Betrieb des EPA (Adapter Anwendung zur Übertragung von Anträgen in die Sparda Baufinanzierung) bei uns einen entsprechenden Incident Prozess vor, welcher eine manuell angestoßene Verarbeitung fehlgeschlagener Abholungen vorsieht.

Wie angemerkt und auch zwischen Frau Kränz und Herrn Kutz besprochen, fänden wir es gut, wenn technische Probleme mittels einfacher Telefonate geklärt werden könnten.
Ein Ticket Prozess über github dauert oft Wochen und ist unserer Ansicht nicht immer zielführend. 
Lt. Aussage von Herrn Kutz haben die Entwickler bei Europace keine festen Durchwahlnummern mehr - ich bin aber unter Telefon: +49 911 9291-2532 erreichbar.

Vielen Dank.
Mit freundlichen Grüßen
i. A. Andreas Tauber

**Comment by u00kram** [comment]
Hier auch nochmal ein aktueller Antrag mit dem OAuth Fehler: (Institut Nbg.)

2967 	7609	 3	1	U76267		09.07.19 16:25:22,511000000	09.07.19 16:25:22,352000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag U76267/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

**Comment by caspii** [comment]
Hallo Zusammen,

Oliver (@ollio ) und ich haben gestern noch mal die Sache besprochen. Mein Verständnis ist, dass diese Fehler im promille Bereich auftreten. Das ist bei einer Web-API nicht unüblich. Euer Client sollte in der Lage sein, mit fehlerhaften Antworten umzugehen.

Hier ist zB eine Anleitung, wie der Retrofit Client auf Fehler regieren kann: https://stackoverflow.com/questions/24562716/how-to-retry-http-requests-with-okhttp-retrofit
