### ISSUE TITLE
Fehler: Gateway Timeout 

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#46]
Bitte die Ursache für das Gateway Timeout anschauen. Den Antrag haben wir per Wiederholung mit der Antragsnummer abgeholt. 

1117	6009	1	1	Y41341		01.04.19 12:46:23,814000000	01.04.19 12:46:23,334000000	FEHLER	de.sdvrz.epa.europace.EuropaceApiException	EuropaceApiException: Fehler bei getAntrag Y41341/1	"de.sdvrz.epa.europace.EuropaceApiException: Fehler bei getAntrag Y41341/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:101)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)
	at de.sdvrz.epa.core.EpaControl.starteMapping(EpaControl.java:281)
	at de.sdvrz.epa.core.EpaControl.verarbeiteAntrag(EpaControl.java:234)
	at de.sdvrz.epa.core.EpaControl.lambda$verarbeiteEuropaceAntraege$0(EpaControl.java:195)
	at java.util.Optional.ifPresent(Optional.java:159)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEuropaceAntraege(EpaControl.java:183)
	at de.sdvrz.epa.core.EpaControl.verarbeiteEpaKonfig(EpaControl.java:112)
	at de.sdvrz.epa.core.EpaControl.verarbeiteMandanten(EpaControl.java:85)
	at de.sdvrz.epa.core.EpaScheduler.epaAblauf(EpaScheduler.java:73)
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383)
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250)
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
"

Folgendes ist dem Server.log zu entnehmen:

>>>
2019-04-01 12:46:23,795 ERROR [de.sdvrz.epa.europace.AntraegeApiDelegate] (EE-ManagedScheduledExecutorService-epascheduler-Thread-1) Antrag Y41341/1 Http Code: 504 Message: Gateway Timeout 
2019-04-01 12:46:23,805 ERROR [de.sdvrz.epa.core.EpaScheduler] (EE-ManagedScheduledExecutorService-epascheduler-Thread-1) Fehler bei Vorgang Y41341 Antrag 1: de.sdvrz.epa.europace.EuropaceApiException: Fehler bei getAntrag Y41341/1 at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:101) [classes:] at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77) [classes:] at de.sdvrz.epa.core.EpaControl.starteMapping(EpaControl.java:281) [classes:] at de.sdvrz.epa.core.EpaControl.verarbeiteAntrag(EpaControl.java:234) [classes:] at de.sdvrz.epa.core.EpaControl.lambda$verarbeiteEuropaceAntraege$0(EpaControl.java:195) [classes:] at java.util.Optional.ifPresent(Optional.java:159) [rt.jar:1.8.0_201] at de.sdvrz.epa.core.EpaControl.verarbeiteEuropaceAntraege(EpaControl.java:183) [classes:] at de.sdvrz.epa.core.EpaControl.verarbeiteEpaKonfig(EpaControl.java:112) [classes:] at de.sdvrz.epa.core.EpaControl.verarbeiteMandanten(EpaControl.java:85) [classes:] at de.sdvrz.epa.core.EpaScheduler.epaAblauf(EpaScheduler.java:73) [classes:] at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158) [wildfly-ee-14.0.1.Final.jar:14.0.1.Final] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_201] at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [rt.jar:1.8.0_201] at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383) [javax.enterprise.concurrent-1.0.jar:] at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534) [javax.enterprise.concurrent-1.0.jar:] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_201] at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_201] at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) [javax.enterprise.concurrent-1.0.jar:] at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78)
>>>

**Comment by oliverharendt** [comment]
@u00kram Ist der Fehler hier nochmal aufgetreten oder können wir das Ticket schließen?

**Comment by u00kram** [comment]
Hallo Oliver - ja der Fehler tritt immer mal wieder sporadisch auf. 
Fehler am 6.3.20 bei der SpB BW. VG, Manuela 

ID, INSTITUT, EPA_KONFIG_ID, EPA_ANTRAG, EPA_VORGANG, GLOBO_KVGID, AKTUALISIERUNG, ERSTELLUNG, EPA_STATUS, EXCEPTION, MESSAGE, STACKTRACE
9948	6009	1	1	BR53MV		06.03.20 10:01:03,847000000	06.03.20 10:01:03,617000000	FEHLER	org.apache.oltu.oauth2.common.exception.OAuthProblemException	OAuthProblemException: invalid_request, Missing parameters: access_token	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag BR53MV/1

**Comment by u00kram** [comment]
Hallo Oliver,
wir haben wieder zwei neue Anträge mit dem Fehler. Gibt es denn dazu neue Erkenntnisse?
Danke und VG, Manuela 

Sparda Bank BW / 
11221 6009 1 2 S69AXP 16.04.20 17:40:38,171000000 16.04.20 17:40:37,127000000 FEHLER de.sdvrz.epa.europace.EuropaceApiException EuropaceApiException: Keine Antraege in Response Body bei getAntrag fuer S69AXP/2 "de.sdvrz.epa.europace.EuropaceApiException: Keine Antraege in Response Body bei getAntrag fuer S69AXP/2

11151 6009 1 2 QW0KC3 15.04.20 09:45:30,345000000 15.04.20 09:45:29,805000000 FEHLER de.sdvrz.epa.europace.EuropaceApiException EuropaceApiException: Keine Antraege in Response Body bei getAntrag fuer QW0KC3/2 "de.sdvrz.epa.europace.EuropaceApiException: Keine Antraege in Response Body bei getAntrag fuer QW0KC3/2

**Comment by u00kram** [comment]
Noch ein Antrag - nun bei der SpB München

11252	7009	2	1	LK1K5W		17.04.20 11:44:41,819000000	17.04.20 11:44:41,219000000	FEHLER	de.sdvrz.epa.europace.EuropaceApiException	EuropaceApiException: Fehler bei getAntrag LK1K5W/1	"de.sdvrz.epa.europace.EuropaceApiException: Fehler bei getAntrag LK1K5W/1

**Comment by u00kram** [comment]
Zusammenfassung:
In dem Ticket haben sich inzwischen 3 Fehlerarten zusammengeschlichen.
Nach Absprache in der Telko vom 22.4.20 wird in dem Issue nur folgender Fehler behandelt:
... EuropaceApiException: Fehler bei getAntrag LK1K5W/1 "de.sdvrz.epa.europace.EuropaceApiException: Fehler bei getAntrag LK1K5W/1 ...

Sollten die anderen beiden Fehler wiederholt auftreten, wird ein eigenes Issue eröffnet.

**Comment by oliverharendt** [comment]
Erste Erkenntnisse hierzu: 
Der Fehler scheint aufzutreten, wenn das Abholen eines einzelnen Antrags sehr nah an seiner Erstellungszeit liegt. Es sieht so aus, als würde `getAlleAntraege()` Anträge ausliefern, die noch nicht über `getAntrag()` ausgelesen werden können.

**Comment by u00kram** [comment]
Hallo Oliver, 
hier die aktuelle Fehlersituation.
Die ersten beiden Fehlermeldungen sind etwas anders als die dritte Fehlermeldung - aber es fehlen immer die Responsedaten, was eventuell auf den gleichen Grund der Fehler hinweist?! Das müsst ihr nun ermitteln. Danke dafür.
Gibt es denn schon eine Lösung für das Problem? 
Wir sind am 27.5.20 / 14:30 Uhr per Telko verabredet.
Danke und VG, Manuela 

Sparda-Bank München / ohne Response-Daten
12387	7009	2	2	Q29NB6		20.05.20 12:02:01,009000000	20.05.20 12:01:50,682000000	FEHLER	java.net.SocketException	SocketException: Socket closed	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag Q29NB6/2
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

Sparda-Bank Hessen /  ohne Response-Daten
12388	5009	4	1	X13QUS		20.05.20 12:19:51,843000000	20.05.20 12:19:41,495000000	FEHLER	java.net.SocketException	SocketException: Socket closed	"de.sdvrz.epa.europace.EuropaceApiException: IO Fehler bei getAntrag X13QUS/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:123)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

Sparda-Bank BW / bekannte Fehlermeldung
12390	6009	1	1	PR73WD		20.05.20 13:00:07,247000000	20.05.20 12:20:08,564000000	FEHLER	de.sdvrz.epa.europace.EuropaceApiException	EuropaceApiException: Fehler bei getAntrag PR73WD/1	"de.sdvrz.epa.europace.EuropaceApiException: Fehler bei getAntrag PR73WD/1
	at de.sdvrz.epa.europace.AntraegeApiDelegate.holeAntrag(AntraegeApiDelegate.java:106)
	at de.sdvrz.epa.mapping.AntragMappingTask.call(AntragMappingTask.java:77)

Response-Daten hierzu:
EPA_VORGANG, EPA_ANTRAG, ERSTELLUNG, GLOBO_KVGID, HTTP_REPSPONSE_STRUKTUR
PR73WD	1	20.05.20 12:20:08,564000000

**Comment by u00kram** [comment]
Nachtrag zum vorigen Kommentar:
Der Fehlerfall (bei BW) hatte im ersten Abholversuch die gleiche Fehlermeldung wie die andern von Hessen und München. Der obige Fehler bei BW ist erst bei der wiederholten Abholung ausgegeben worden. 
Also sprechen wir von 3 gleichen Fehlern.

**Comment by oliverharendt** [comment]
Ich möchte hier eine kleine Rückmeldung geben.
Wir sind an dem Problem dran, dass der angefragte Antrag manchmal nicht geliefert wird, obwohl er existiert. Wir haben mittlerweile identifiziert wo sich der Fehler versteckt hat und suchen grad nach einer geeigneten Lösung. 
Ohne Genaueres zu verraten handelt es sich um einen Cachingfehler bei uns, der immer dann auftritt, wenn zu einem Vorgang mehrere Anträge kurz hintereinander erzeugt werden und dazwischen eine Abfrage zu einem der Anträge über die API erfolgt.

**Comment by oliverharendt** [comment]
Ab heute sollte das Problem der Rückgabe von leeren Anträgen behoben sein. Ich würde daher dieses Issue schließen wollen.
@u00kram Falls der Fehler in den nächsten Tagen nochmal auftreten sollte macht dieses Issue einfach wieder auf. Ansonsten sehen wir das Thema als erledigt an.
